// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gauge.proto

package metric;

public final class GaugeOuterClass {
	private GaugeOuterClass() {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
	}

	public interface GaugeOrBuilder extends
			// @@protoc_insertion_point(interface_extends:metric.Gauge)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <pre>
		 * Gauge Metric Name
		 * </pre>
		 *
		 * <code>string name = 1;</code>
		 * 
		 * @return The name.
		 */
		java.lang.String getName();

		/**
		 * <pre>
		 * Gauge Metric Name
		 * </pre>
		 *
		 * <code>string name = 1;</code>
		 * 
		 * @return The bytes for name.
		 */
		com.google.protobuf.ByteString getNameBytes();

		/**
		 * <pre>
		 * Gauge Metric Description
		 * </pre>
		 *
		 * <code>string description = 2;</code>
		 * 
		 * @return The description.
		 */
		java.lang.String getDescription();

		/**
		 * <pre>
		 * Gauge Metric Description
		 * </pre>
		 *
		 * <code>string description = 2;</code>
		 * 
		 * @return The bytes for description.
		 */
		com.google.protobuf.ByteString getDescriptionBytes();

		/**
		 * <pre>
		 * Gauge Metric Value
		 * </pre>
		 *
		 * <code>int64 value = 3;</code>
		 * 
		 * @return The value.
		 */
		long getValue();

		/**
		 * <pre>
		 * Gauge Metric Unit
		 * </pre>
		 *
		 * <code>string unit = 4;</code>
		 * 
		 * @return The unit.
		 */
		java.lang.String getUnit();

		/**
		 * <pre>
		 * Gauge Metric Unit
		 * </pre>
		 *
		 * <code>string unit = 4;</code>
		 * 
		 * @return The bytes for unit.
		 */
		com.google.protobuf.ByteString getUnitBytes();

		/**
		 * <pre>
		 * Metric Headers like : HostIPAddress
		 * </pre>
		 *
		 * <code>map&lt;string, string&gt; properties = 5;</code>
		 */
		int getPropertiesCount();

		/**
		 * <pre>
		 * Metric Headers like : HostIPAddress
		 * </pre>
		 *
		 * <code>map&lt;string, string&gt; properties = 5;</code>
		 */
		boolean containsProperties(java.lang.String key);

		/**
		 * Use {@link #getPropertiesMap()} instead.
		 */
		@java.lang.Deprecated
		java.util.Map<java.lang.String, java.lang.String> getProperties();

		/**
		 * <pre>
		 * Metric Headers like : HostIPAddress
		 * </pre>
		 *
		 * <code>map&lt;string, string&gt; properties = 5;</code>
		 */
		java.util.Map<java.lang.String, java.lang.String> getPropertiesMap();

		/**
		 * <pre>
		 * Metric Headers like : HostIPAddress
		 * </pre>
		 *
		 * <code>map&lt;string, string&gt; properties = 5;</code>
		 */

		java.lang.String getPropertiesOrDefault(java.lang.String key, java.lang.String defaultValue);

		/**
		 * <pre>
		 * Metric Headers like : HostIPAddress
		 * </pre>
		 *
		 * <code>map&lt;string, string&gt; properties = 5;</code>
		 */

		java.lang.String getPropertiesOrThrow(java.lang.String key);
	}

	/**
	 * Protobuf type {@code metric.Gauge}
	 */
	public static final class Gauge extends com.google.protobuf.GeneratedMessageV3 implements
			// @@protoc_insertion_point(message_implements:metric.Gauge)
			GaugeOrBuilder {
		private static final long serialVersionUID = 0L;

		// Use Gauge.newBuilder() to construct.
		private Gauge(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private Gauge() {
			name_ = "";
			description_ = "";
			unit_ = "";
		}

		@java.lang.Override
		@SuppressWarnings({ "unused" })
		protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
			return new Gauge();
		}

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private Gauge(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			if (extensionRegistry == null) {
				throw new java.lang.NullPointerException();
			}
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
					.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					case 10: {
						java.lang.String s = input.readStringRequireUtf8();

						name_ = s;
						break;
					}
					case 18: {
						java.lang.String s = input.readStringRequireUtf8();

						description_ = s;
						break;
					}
					case 24: {

						value_ = input.readInt64();
						break;
					}
					case 34: {
						java.lang.String s = input.readStringRequireUtf8();

						unit_ = s;
						break;
					}
					case 42: {
						if (!((mutable_bitField0_ & 0x00000001) != 0)) {
							properties_ = com.google.protobuf.MapField
									.newMapField(PropertiesDefaultEntryHolder.defaultEntry);
							mutable_bitField0_ |= 0x00000001;
						}
						com.google.protobuf.MapEntry<java.lang.String, java.lang.String> properties__ = input
								.readMessage(PropertiesDefaultEntryHolder.defaultEntry.getParserForType(),
										extensionRegistry);
						properties_.getMutableMap().put(properties__.getKey(), properties__.getValue());
						break;
					}
					default: {
						if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return metric.GaugeOuterClass.internal_static_metric_Gauge_descriptor;
		}

		@SuppressWarnings({ "rawtypes" })
		@java.lang.Override
		protected com.google.protobuf.MapField internalGetMapField(int number) {
			switch (number) {
			case 5:
				return internalGetProperties();
			default:
				throw new RuntimeException("Invalid map field number: " + number);
			}
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return metric.GaugeOuterClass.internal_static_metric_Gauge_fieldAccessorTable
					.ensureFieldAccessorsInitialized(metric.GaugeOuterClass.Gauge.class,
							metric.GaugeOuterClass.Gauge.Builder.class);
		}

		public static final int NAME_FIELD_NUMBER = 1;
		private volatile java.lang.Object name_;

		/**
		 * <pre>
		 * Gauge Metric Name
		 * </pre>
		 *
		 * <code>string name = 1;</code>
		 * 
		 * @return The name.
		 */
		public java.lang.String getName() {
			java.lang.Object ref = name_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				name_ = s;
				return s;
			}
		}

		/**
		 * <pre>
		 * Gauge Metric Name
		 * </pre>
		 *
		 * <code>string name = 1;</code>
		 * 
		 * @return The bytes for name.
		 */
		public com.google.protobuf.ByteString getNameBytes() {
			java.lang.Object ref = name_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				name_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int DESCRIPTION_FIELD_NUMBER = 2;
		private volatile java.lang.Object description_;

		/**
		 * <pre>
		 * Gauge Metric Description
		 * </pre>
		 *
		 * <code>string description = 2;</code>
		 * 
		 * @return The description.
		 */
		public java.lang.String getDescription() {
			java.lang.Object ref = description_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				description_ = s;
				return s;
			}
		}

		/**
		 * <pre>
		 * Gauge Metric Description
		 * </pre>
		 *
		 * <code>string description = 2;</code>
		 * 
		 * @return The bytes for description.
		 */
		public com.google.protobuf.ByteString getDescriptionBytes() {
			java.lang.Object ref = description_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				description_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int VALUE_FIELD_NUMBER = 3;
		private long value_;

		/**
		 * <pre>
		 * Gauge Metric Value
		 * </pre>
		 *
		 * <code>int64 value = 3;</code>
		 * 
		 * @return The value.
		 */
		public long getValue() {
			return value_;
		}

		public static final int UNIT_FIELD_NUMBER = 4;
		private volatile java.lang.Object unit_;

		/**
		 * <pre>
		 * Gauge Metric Unit
		 * </pre>
		 *
		 * <code>string unit = 4;</code>
		 * 
		 * @return The unit.
		 */
		public java.lang.String getUnit() {
			java.lang.Object ref = unit_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				unit_ = s;
				return s;
			}
		}

		/**
		 * <pre>
		 * Gauge Metric Unit
		 * </pre>
		 *
		 * <code>string unit = 4;</code>
		 * 
		 * @return The bytes for unit.
		 */
		public com.google.protobuf.ByteString getUnitBytes() {
			java.lang.Object ref = unit_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				unit_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int PROPERTIES_FIELD_NUMBER = 5;

		private static final class PropertiesDefaultEntryHolder {
			static final com.google.protobuf.MapEntry<java.lang.String, java.lang.String> defaultEntry = com.google.protobuf.MapEntry.<java.lang.String, java.lang.String>newDefaultInstance(
					metric.GaugeOuterClass.internal_static_metric_Gauge_PropertiesEntry_descriptor,
					com.google.protobuf.WireFormat.FieldType.STRING, "",
					com.google.protobuf.WireFormat.FieldType.STRING, "");
		}

		private com.google.protobuf.MapField<java.lang.String, java.lang.String> properties_;

		private com.google.protobuf.MapField<java.lang.String, java.lang.String> internalGetProperties() {
			if (properties_ == null) {
				return com.google.protobuf.MapField.emptyMapField(PropertiesDefaultEntryHolder.defaultEntry);
			}
			return properties_;
		}

		public int getPropertiesCount() {
			return internalGetProperties().getMap().size();
		}

		/**
		 * <pre>
		 * Metric Headers like : HostIPAddress
		 * </pre>
		 *
		 * <code>map&lt;string, string&gt; properties = 5;</code>
		 */

		public boolean containsProperties(java.lang.String key) {
			if (key == null) {
				throw new java.lang.NullPointerException();
			}
			return internalGetProperties().getMap().containsKey(key);
		}

		/**
		 * Use {@link #getPropertiesMap()} instead.
		 */
		@java.lang.Deprecated
		public java.util.Map<java.lang.String, java.lang.String> getProperties() {
			return getPropertiesMap();
		}

		/**
		 * <pre>
		 * Metric Headers like : HostIPAddress
		 * </pre>
		 *
		 * <code>map&lt;string, string&gt; properties = 5;</code>
		 */

		public java.util.Map<java.lang.String, java.lang.String> getPropertiesMap() {
			return internalGetProperties().getMap();
		}

		/**
		 * <pre>
		 * Metric Headers like : HostIPAddress
		 * </pre>
		 *
		 * <code>map&lt;string, string&gt; properties = 5;</code>
		 */

		public java.lang.String getPropertiesOrDefault(java.lang.String key, java.lang.String defaultValue) {
			if (key == null) {
				throw new java.lang.NullPointerException();
			}
			java.util.Map<java.lang.String, java.lang.String> map = internalGetProperties().getMap();
			return map.containsKey(key) ? map.get(key) : defaultValue;
		}

		/**
		 * <pre>
		 * Metric Headers like : HostIPAddress
		 * </pre>
		 *
		 * <code>map&lt;string, string&gt; properties = 5;</code>
		 */

		public java.lang.String getPropertiesOrThrow(java.lang.String key) {
			if (key == null) {
				throw new java.lang.NullPointerException();
			}
			java.util.Map<java.lang.String, java.lang.String> map = internalGetProperties().getMap();
			if (!map.containsKey(key)) {
				throw new java.lang.IllegalArgumentException();
			}
			return map.get(key);
		}

		private byte memoizedIsInitialized = -1;

		@java.lang.Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1)
				return true;
			if (isInitialized == 0)
				return false;

			memoizedIsInitialized = 1;
			return true;
		}

		@java.lang.Override
		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			if (!getNameBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
			}
			if (!getDescriptionBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 2, description_);
			}
			if (value_ != 0L) {
				output.writeInt64(3, value_);
			}
			if (!getUnitBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 4, unit_);
			}
			com.google.protobuf.GeneratedMessageV3.serializeStringMapTo(output, internalGetProperties(),
					PropertiesDefaultEntryHolder.defaultEntry, 5);
			unknownFields.writeTo(output);
		}

		@java.lang.Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1)
				return size;

			size = 0;
			if (!getNameBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
			}
			if (!getDescriptionBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, description_);
			}
			if (value_ != 0L) {
				size += com.google.protobuf.CodedOutputStream.computeInt64Size(3, value_);
			}
			if (!getUnitBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, unit_);
			}
			for (java.util.Map.Entry<java.lang.String, java.lang.String> entry : internalGetProperties().getMap()
					.entrySet()) {
				com.google.protobuf.MapEntry<java.lang.String, java.lang.String> properties__ = PropertiesDefaultEntryHolder.defaultEntry
						.newBuilderForType().setKey(entry.getKey()).setValue(entry.getValue()).build();
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(5, properties__);
			}
			size += unknownFields.getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof metric.GaugeOuterClass.Gauge)) {
				return super.equals(obj);
			}
			metric.GaugeOuterClass.Gauge other = (metric.GaugeOuterClass.Gauge) obj;

			if (!getName().equals(other.getName()))
				return false;
			if (!getDescription().equals(other.getDescription()))
				return false;
			if (getValue() != other.getValue())
				return false;
			if (!getUnit().equals(other.getUnit()))
				return false;
			if (!internalGetProperties().equals(other.internalGetProperties()))
				return false;
			if (!unknownFields.equals(other.unknownFields))
				return false;
			return true;
		}

		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			hash = (37 * hash) + NAME_FIELD_NUMBER;
			hash = (53 * hash) + getName().hashCode();
			hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
			hash = (53 * hash) + getDescription().hashCode();
			hash = (37 * hash) + VALUE_FIELD_NUMBER;
			hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getValue());
			hash = (37 * hash) + UNIT_FIELD_NUMBER;
			hash = (53 * hash) + getUnit().hashCode();
			if (!internalGetProperties().getMap().isEmpty()) {
				hash = (37 * hash) + PROPERTIES_FIELD_NUMBER;
				hash = (53 * hash) + internalGetProperties().hashCode();
			}
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static metric.GaugeOuterClass.Gauge parseFrom(java.nio.ByteBuffer data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static metric.GaugeOuterClass.Gauge parseFrom(java.nio.ByteBuffer data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static metric.GaugeOuterClass.Gauge parseFrom(com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static metric.GaugeOuterClass.Gauge parseFrom(com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static metric.GaugeOuterClass.Gauge parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static metric.GaugeOuterClass.Gauge parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static metric.GaugeOuterClass.Gauge parseFrom(java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}

		public static metric.GaugeOuterClass.Gauge parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static metric.GaugeOuterClass.Gauge parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
		}

		public static metric.GaugeOuterClass.Gauge parseDelimitedFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
					extensionRegistry);
		}

		public static metric.GaugeOuterClass.Gauge parseFrom(com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}

		public static metric.GaugeOuterClass.Gauge parseFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		@java.lang.Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(metric.GaugeOuterClass.Gauge prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		@java.lang.Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code metric.Gauge}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
				// @@protoc_insertion_point(builder_implements:metric.Gauge)
				metric.GaugeOuterClass.GaugeOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return metric.GaugeOuterClass.internal_static_metric_Gauge_descriptor;
			}

			@SuppressWarnings({ "rawtypes" })
			protected com.google.protobuf.MapField internalGetMapField(int number) {
				switch (number) {
				case 5:
					return internalGetProperties();
				default:
					throw new RuntimeException("Invalid map field number: " + number);
				}
			}

			@SuppressWarnings({ "rawtypes" })
			protected com.google.protobuf.MapField internalGetMutableMapField(int number) {
				switch (number) {
				case 5:
					return internalGetMutableProperties();
				default:
					throw new RuntimeException("Invalid map field number: " + number);
				}
			}

			@java.lang.Override
			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
				return metric.GaugeOuterClass.internal_static_metric_Gauge_fieldAccessorTable
						.ensureFieldAccessorsInitialized(metric.GaugeOuterClass.Gauge.class,
								metric.GaugeOuterClass.Gauge.Builder.class);
			}

			// Construct using metric.GaugeOuterClass.Gauge.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
				}
			}

			@java.lang.Override
			public Builder clear() {
				super.clear();
				name_ = "";

				description_ = "";

				value_ = 0L;

				unit_ = "";

				internalGetMutableProperties().clear();
				return this;
			}

			@java.lang.Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return metric.GaugeOuterClass.internal_static_metric_Gauge_descriptor;
			}

			@java.lang.Override
			public metric.GaugeOuterClass.Gauge getDefaultInstanceForType() {
				return metric.GaugeOuterClass.Gauge.getDefaultInstance();
			}

			@java.lang.Override
			public metric.GaugeOuterClass.Gauge build() {
				metric.GaugeOuterClass.Gauge result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@java.lang.Override
			public metric.GaugeOuterClass.Gauge buildPartial() {
				metric.GaugeOuterClass.Gauge result = new metric.GaugeOuterClass.Gauge(this);
				int from_bitField0_ = bitField0_;
				result.name_ = name_;
				result.description_ = description_;
				result.value_ = value_;
				result.unit_ = unit_;
				result.properties_ = internalGetProperties();
				result.properties_.makeImmutable();
				onBuilt();
				return result;
			}

			@java.lang.Override
			public Builder clone() {
				return super.clone();
			}

			@java.lang.Override
			public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
				return super.setField(field, value);
			}

			@java.lang.Override
			public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
				return super.clearField(field);
			}

			@java.lang.Override
			public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return super.clearOneof(oneof);
			}

			@java.lang.Override
			public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
					java.lang.Object value) {
				return super.setRepeatedField(field, index, value);
			}

			@java.lang.Override
			public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
					java.lang.Object value) {
				return super.addRepeatedField(field, value);
			}

			@java.lang.Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof metric.GaugeOuterClass.Gauge) {
					return mergeFrom((metric.GaugeOuterClass.Gauge) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(metric.GaugeOuterClass.Gauge other) {
				if (other == metric.GaugeOuterClass.Gauge.getDefaultInstance())
					return this;
				if (!other.getName().isEmpty()) {
					name_ = other.name_;
					onChanged();
				}
				if (!other.getDescription().isEmpty()) {
					description_ = other.description_;
					onChanged();
				}
				if (other.getValue() != 0L) {
					setValue(other.getValue());
				}
				if (!other.getUnit().isEmpty()) {
					unit_ = other.unit_;
					onChanged();
				}
				internalGetMutableProperties().mergeFrom(other.internalGetProperties());
				this.mergeUnknownFields(other.unknownFields);
				onChanged();
				return this;
			}

			@java.lang.Override
			public final boolean isInitialized() {
				return true;
			}

			@java.lang.Override
			public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				metric.GaugeOuterClass.Gauge parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (metric.GaugeOuterClass.Gauge) e.getUnfinishedMessage();
					throw e.unwrapIOException();
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			private java.lang.Object name_ = "";

			/**
			 * <pre>
			 * Gauge Metric Name
			 * </pre>
			 *
			 * <code>string name = 1;</code>
			 * 
			 * @return The name.
			 */
			public java.lang.String getName() {
				java.lang.Object ref = name_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					name_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <pre>
			 * Gauge Metric Name
			 * </pre>
			 *
			 * <code>string name = 1;</code>
			 * 
			 * @return The bytes for name.
			 */
			public com.google.protobuf.ByteString getNameBytes() {
				java.lang.Object ref = name_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					name_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <pre>
			 * Gauge Metric Name
			 * </pre>
			 *
			 * <code>string name = 1;</code>
			 * 
			 * @param value The name to set.
			 * @return This builder for chaining.
			 */
			public Builder setName(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				name_ = value;
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * Gauge Metric Name
			 * </pre>
			 *
			 * <code>string name = 1;</code>
			 * 
			 * @return This builder for chaining.
			 */
			public Builder clearName() {

				name_ = getDefaultInstance().getName();
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * Gauge Metric Name
			 * </pre>
			 *
			 * <code>string name = 1;</code>
			 * 
			 * @param value The bytes for name to set.
			 * @return This builder for chaining.
			 */
			public Builder setNameBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				name_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object description_ = "";

			/**
			 * <pre>
			 * Gauge Metric Description
			 * </pre>
			 *
			 * <code>string description = 2;</code>
			 * 
			 * @return The description.
			 */
			public java.lang.String getDescription() {
				java.lang.Object ref = description_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					description_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <pre>
			 * Gauge Metric Description
			 * </pre>
			 *
			 * <code>string description = 2;</code>
			 * 
			 * @return The bytes for description.
			 */
			public com.google.protobuf.ByteString getDescriptionBytes() {
				java.lang.Object ref = description_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					description_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <pre>
			 * Gauge Metric Description
			 * </pre>
			 *
			 * <code>string description = 2;</code>
			 * 
			 * @param value The description to set.
			 * @return This builder for chaining.
			 */
			public Builder setDescription(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				description_ = value;
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * Gauge Metric Description
			 * </pre>
			 *
			 * <code>string description = 2;</code>
			 * 
			 * @return This builder for chaining.
			 */
			public Builder clearDescription() {

				description_ = getDefaultInstance().getDescription();
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * Gauge Metric Description
			 * </pre>
			 *
			 * <code>string description = 2;</code>
			 * 
			 * @param value The bytes for description to set.
			 * @return This builder for chaining.
			 */
			public Builder setDescriptionBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				description_ = value;
				onChanged();
				return this;
			}

			private long value_;

			/**
			 * <pre>
			 * Gauge Metric Value
			 * </pre>
			 *
			 * <code>int64 value = 3;</code>
			 * 
			 * @return The value.
			 */
			public long getValue() {
				return value_;
			}

			/**
			 * <pre>
			 * Gauge Metric Value
			 * </pre>
			 *
			 * <code>int64 value = 3;</code>
			 * 
			 * @param value The value to set.
			 * @return This builder for chaining.
			 */
			public Builder setValue(long value) {

				value_ = value;
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * Gauge Metric Value
			 * </pre>
			 *
			 * <code>int64 value = 3;</code>
			 * 
			 * @return This builder for chaining.
			 */
			public Builder clearValue() {

				value_ = 0L;
				onChanged();
				return this;
			}

			private java.lang.Object unit_ = "";

			/**
			 * <pre>
			 * Gauge Metric Unit
			 * </pre>
			 *
			 * <code>string unit = 4;</code>
			 * 
			 * @return The unit.
			 */
			public java.lang.String getUnit() {
				java.lang.Object ref = unit_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					unit_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <pre>
			 * Gauge Metric Unit
			 * </pre>
			 *
			 * <code>string unit = 4;</code>
			 * 
			 * @return The bytes for unit.
			 */
			public com.google.protobuf.ByteString getUnitBytes() {
				java.lang.Object ref = unit_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					unit_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <pre>
			 * Gauge Metric Unit
			 * </pre>
			 *
			 * <code>string unit = 4;</code>
			 * 
			 * @param value The unit to set.
			 * @return This builder for chaining.
			 */
			public Builder setUnit(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				unit_ = value;
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * Gauge Metric Unit
			 * </pre>
			 *
			 * <code>string unit = 4;</code>
			 * 
			 * @return This builder for chaining.
			 */
			public Builder clearUnit() {

				unit_ = getDefaultInstance().getUnit();
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * Gauge Metric Unit
			 * </pre>
			 *
			 * <code>string unit = 4;</code>
			 * 
			 * @param value The bytes for unit to set.
			 * @return This builder for chaining.
			 */
			public Builder setUnitBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				unit_ = value;
				onChanged();
				return this;
			}

			private com.google.protobuf.MapField<java.lang.String, java.lang.String> properties_;

			private com.google.protobuf.MapField<java.lang.String, java.lang.String> internalGetProperties() {
				if (properties_ == null) {
					return com.google.protobuf.MapField.emptyMapField(PropertiesDefaultEntryHolder.defaultEntry);
				}
				return properties_;
			}

			private com.google.protobuf.MapField<java.lang.String, java.lang.String> internalGetMutableProperties() {
				onChanged();
				;
				if (properties_ == null) {
					properties_ = com.google.protobuf.MapField.newMapField(PropertiesDefaultEntryHolder.defaultEntry);
				}
				if (!properties_.isMutable()) {
					properties_ = properties_.copy();
				}
				return properties_;
			}

			public int getPropertiesCount() {
				return internalGetProperties().getMap().size();
			}

			/**
			 * <pre>
			 * Metric Headers like : HostIPAddress
			 * </pre>
			 *
			 * <code>map&lt;string, string&gt; properties = 5;</code>
			 */

			public boolean containsProperties(java.lang.String key) {
				if (key == null) {
					throw new java.lang.NullPointerException();
				}
				return internalGetProperties().getMap().containsKey(key);
			}

			/**
			 * Use {@link #getPropertiesMap()} instead.
			 */
			@java.lang.Deprecated
			public java.util.Map<java.lang.String, java.lang.String> getProperties() {
				return getPropertiesMap();
			}

			/**
			 * <pre>
			 * Metric Headers like : HostIPAddress
			 * </pre>
			 *
			 * <code>map&lt;string, string&gt; properties = 5;</code>
			 */

			public java.util.Map<java.lang.String, java.lang.String> getPropertiesMap() {
				return internalGetProperties().getMap();
			}

			/**
			 * <pre>
			 * Metric Headers like : HostIPAddress
			 * </pre>
			 *
			 * <code>map&lt;string, string&gt; properties = 5;</code>
			 */

			public java.lang.String getPropertiesOrDefault(java.lang.String key, java.lang.String defaultValue) {
				if (key == null) {
					throw new java.lang.NullPointerException();
				}
				java.util.Map<java.lang.String, java.lang.String> map = internalGetProperties().getMap();
				return map.containsKey(key) ? map.get(key) : defaultValue;
			}

			/**
			 * <pre>
			 * Metric Headers like : HostIPAddress
			 * </pre>
			 *
			 * <code>map&lt;string, string&gt; properties = 5;</code>
			 */

			public java.lang.String getPropertiesOrThrow(java.lang.String key) {
				if (key == null) {
					throw new java.lang.NullPointerException();
				}
				java.util.Map<java.lang.String, java.lang.String> map = internalGetProperties().getMap();
				if (!map.containsKey(key)) {
					throw new java.lang.IllegalArgumentException();
				}
				return map.get(key);
			}

			public Builder clearProperties() {
				internalGetMutableProperties().getMutableMap().clear();
				return this;
			}

			/**
			 * <pre>
			 * Metric Headers like : HostIPAddress
			 * </pre>
			 *
			 * <code>map&lt;string, string&gt; properties = 5;</code>
			 */

			public Builder removeProperties(java.lang.String key) {
				if (key == null) {
					throw new java.lang.NullPointerException();
				}
				internalGetMutableProperties().getMutableMap().remove(key);
				return this;
			}

			/**
			 * Use alternate mutation accessors instead.
			 */
			@java.lang.Deprecated
			public java.util.Map<java.lang.String, java.lang.String> getMutableProperties() {
				return internalGetMutableProperties().getMutableMap();
			}

			/**
			 * <pre>
			 * Metric Headers like : HostIPAddress
			 * </pre>
			 *
			 * <code>map&lt;string, string&gt; properties = 5;</code>
			 */
			public Builder putProperties(java.lang.String key, java.lang.String value) {
				if (key == null) {
					throw new java.lang.NullPointerException();
				}
				if (value == null) {
					throw new java.lang.NullPointerException();
				}
				internalGetMutableProperties().getMutableMap().put(key, value);
				return this;
			}

			/**
			 * <pre>
			 * Metric Headers like : HostIPAddress
			 * </pre>
			 *
			 * <code>map&lt;string, string&gt; properties = 5;</code>
			 */

			public Builder putAllProperties(java.util.Map<java.lang.String, java.lang.String> values) {
				internalGetMutableProperties().getMutableMap().putAll(values);
				return this;
			}

			@java.lang.Override
			public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFields(unknownFields);
			}

			@java.lang.Override
			public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}

			// @@protoc_insertion_point(builder_scope:metric.Gauge)
		}

		// @@protoc_insertion_point(class_scope:metric.Gauge)
		private static final metric.GaugeOuterClass.Gauge DEFAULT_INSTANCE;
		static {
			DEFAULT_INSTANCE = new metric.GaugeOuterClass.Gauge();
		}

		public static metric.GaugeOuterClass.Gauge getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<Gauge> PARSER = new com.google.protobuf.AbstractParser<Gauge>() {
			@java.lang.Override
			public Gauge parsePartialFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new Gauge(input, extensionRegistry);
			}
		};

		public static com.google.protobuf.Parser<Gauge> parser() {
			return PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<Gauge> getParserForType() {
			return PARSER;
		}

		@java.lang.Override
		public metric.GaugeOuterClass.Gauge getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	private static final com.google.protobuf.Descriptors.Descriptor internal_static_metric_Gauge_descriptor;
	private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_metric_Gauge_fieldAccessorTable;
	private static final com.google.protobuf.Descriptors.Descriptor internal_static_metric_Gauge_PropertiesEntry_descriptor;
	private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_metric_Gauge_PropertiesEntry_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = {
				"\n\013gauge.proto\022\006metric\"\255\001\n\005Gauge\022\014\n\004name\030"
						+ "\001 \001(\t\022\023\n\013description\030\002 \001(\t\022\r\n\005value\030\003 \001("
						+ "\003\022\014\n\004unit\030\004 \001(\t\0221\n\nproperties\030\005 \003(\0132\035.me"
						+ "tric.Gauge.PropertiesEntry\0321\n\017Properties"
						+ "Entry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001b\006p"
						+ "roto3" };
		descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
				new com.google.protobuf.Descriptors.FileDescriptor[] {});
		internal_static_metric_Gauge_descriptor = getDescriptor().getMessageTypes().get(0);
		internal_static_metric_Gauge_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_metric_Gauge_descriptor,
				new java.lang.String[] { "Name", "Description", "Value", "Unit", "Properties", });
		internal_static_metric_Gauge_PropertiesEntry_descriptor = internal_static_metric_Gauge_descriptor
				.getNestedTypes().get(0);
		internal_static_metric_Gauge_PropertiesEntry_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_metric_Gauge_PropertiesEntry_descriptor, new java.lang.String[] { "Key", "Value", });
	}

	// @@protoc_insertion_point(outer_class_scope)
}
