// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package metric;

public final class MessageOuterClass {
	private MessageOuterClass() {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
	}

	public interface MessageOrBuilder extends
			// @@protoc_insertion_point(interface_extends:metric.Message)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <pre>
		 *Metric Namespace
		 * </pre>
		 *
		 * <code>string namespace = 3;</code>
		 * 
		 * @return The namespace.
		 */
		java.lang.String getNamespace();

		/**
		 * <pre>
		 *Metric Namespace
		 * </pre>
		 *
		 * <code>string namespace = 3;</code>
		 * 
		 * @return The bytes for namespace.
		 */
		com.google.protobuf.ByteString getNamespaceBytes();

		/**
		 * <pre>
		 *Metric Process Name
		 * </pre>
		 *
		 * <code>string processName = 4;</code>
		 * 
		 * @return The processName.
		 */
		java.lang.String getProcessName();

		/**
		 * <pre>
		 *Metric Process Name
		 * </pre>
		 *
		 * <code>string processName = 4;</code>
		 * 
		 * @return The bytes for processName.
		 */
		com.google.protobuf.ByteString getProcessNameBytes();

		/**
		 * <pre>
		 *Metric Host Name
		 * </pre>
		 *
		 * <code>string hostName = 5;</code>
		 * 
		 * @return The hostName.
		 */
		java.lang.String getHostName();

		/**
		 * <pre>
		 *Metric Host Name
		 * </pre>
		 *
		 * <code>string hostName = 5;</code>
		 * 
		 * @return The bytes for hostName.
		 */
		com.google.protobuf.ByteString getHostNameBytes();

		/**
		 * <pre>
		 *Matric Publish timestamp
		 * </pre>
		 *
		 * <code>int64 timestampUnix = 6;</code>
		 * 
		 * @return The timestampUnix.
		 */
		long getTimestampUnix();

		/**
		 * <pre>
		 * IPAddress
		 * </pre>
		 *
		 * <code>repeated string address = 7;</code>
		 * 
		 * @return A list containing the address.
		 */
		java.util.List<java.lang.String> getAddressList();

		/**
		 * <pre>
		 * IPAddress
		 * </pre>
		 *
		 * <code>repeated string address = 7;</code>
		 * 
		 * @return The count of address.
		 */
		int getAddressCount();

		/**
		 * <pre>
		 * IPAddress
		 * </pre>
		 *
		 * <code>repeated string address = 7;</code>
		 * 
		 * @param index The index of the element to return.
		 * @return The address at the given index.
		 */
		java.lang.String getAddress(int index);

		/**
		 * <pre>
		 * IPAddress
		 * </pre>
		 *
		 * <code>repeated string address = 7;</code>
		 * 
		 * @param index The index of the value to return.
		 * @return The bytes of the address at the given index.
		 */
		com.google.protobuf.ByteString getAddressBytes(int index);

		/**
		 * <pre>
		 *Metric Headers like  HostIPAddress
		 * </pre>
		 *
		 * <code>map&lt;string, string&gt; properties = 9;</code>
		 */
		int getPropertiesCount();

		/**
		 * <pre>
		 *Metric Headers like  HostIPAddress
		 * </pre>
		 *
		 * <code>map&lt;string, string&gt; properties = 9;</code>
		 */
		boolean containsProperties(java.lang.String key);

		/**
		 * Use {@link #getPropertiesMap()} instead.
		 */
		@java.lang.Deprecated
		java.util.Map<java.lang.String, java.lang.String> getProperties();

		/**
		 * <pre>
		 *Metric Headers like  HostIPAddress
		 * </pre>
		 *
		 * <code>map&lt;string, string&gt; properties = 9;</code>
		 */
		java.util.Map<java.lang.String, java.lang.String> getPropertiesMap();

		/**
		 * <pre>
		 *Metric Headers like  HostIPAddress
		 * </pre>
		 *
		 * <code>map&lt;string, string&gt; properties = 9;</code>
		 */

		java.lang.String getPropertiesOrDefault(java.lang.String key, java.lang.String defaultValue);

		/**
		 * <pre>
		 *Metric Headers like  HostIPAddress
		 * </pre>
		 *
		 * <code>map&lt;string, string&gt; properties = 9;</code>
		 */

		java.lang.String getPropertiesOrThrow(java.lang.String key);

		/**
		 * <code>repeated .metric.Message.Metric metric = 1;</code>
		 */
		java.util.List<metric.MessageOuterClass.Message.Metric> getMetricList();

		/**
		 * <code>repeated .metric.Message.Metric metric = 1;</code>
		 */
		metric.MessageOuterClass.Message.Metric getMetric(int index);

		/**
		 * <code>repeated .metric.Message.Metric metric = 1;</code>
		 */
		int getMetricCount();

		/**
		 * <code>repeated .metric.Message.Metric metric = 1;</code>
		 */
		java.util.List<? extends metric.MessageOuterClass.Message.MetricOrBuilder> getMetricOrBuilderList();

		/**
		 * <code>repeated .metric.Message.Metric metric = 1;</code>
		 */
		metric.MessageOuterClass.Message.MetricOrBuilder getMetricOrBuilder(int index);
	}

	/**
	 * Protobuf type {@code metric.Message}
	 */
	public static final class Message extends com.google.protobuf.GeneratedMessageV3 implements
			// @@protoc_insertion_point(message_implements:metric.Message)
			MessageOrBuilder {
		private static final long serialVersionUID = 0L;

		// Use Message.newBuilder() to construct.
		private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private Message() {
			namespace_ = "";
			processName_ = "";
			hostName_ = "";
			address_ = com.google.protobuf.LazyStringArrayList.EMPTY;
			metric_ = java.util.Collections.emptyList();
		}

		@java.lang.Override
		@SuppressWarnings({ "unused" })
		protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
			return new Message();
		}

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private Message(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			if (extensionRegistry == null) {
				throw new java.lang.NullPointerException();
			}
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
					.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					case 10: {
						if (!((mutable_bitField0_ & 0x00000004) != 0)) {
							metric_ = new java.util.ArrayList<metric.MessageOuterClass.Message.Metric>();
							mutable_bitField0_ |= 0x00000004;
						}
						metric_.add(
								input.readMessage(metric.MessageOuterClass.Message.Metric.parser(), extensionRegistry));
						break;
					}
					case 26: {
						java.lang.String s = input.readStringRequireUtf8();

						namespace_ = s;
						break;
					}
					case 34: {
						java.lang.String s = input.readStringRequireUtf8();

						processName_ = s;
						break;
					}
					case 42: {
						java.lang.String s = input.readStringRequireUtf8();

						hostName_ = s;
						break;
					}
					case 48: {

						timestampUnix_ = input.readInt64();
						break;
					}
					case 58: {
						java.lang.String s = input.readStringRequireUtf8();
						if (!((mutable_bitField0_ & 0x00000001) != 0)) {
							address_ = new com.google.protobuf.LazyStringArrayList();
							mutable_bitField0_ |= 0x00000001;
						}
						address_.add(s);
						break;
					}
					case 74: {
						if (!((mutable_bitField0_ & 0x00000002) != 0)) {
							properties_ = com.google.protobuf.MapField
									.newMapField(PropertiesDefaultEntryHolder.defaultEntry);
							mutable_bitField0_ |= 0x00000002;
						}
						com.google.protobuf.MapEntry<java.lang.String, java.lang.String> properties__ = input
								.readMessage(PropertiesDefaultEntryHolder.defaultEntry.getParserForType(),
										extensionRegistry);
						properties_.getMutableMap().put(properties__.getKey(), properties__.getValue());
						break;
					}
					default: {
						if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
			} finally {
				if (((mutable_bitField0_ & 0x00000004) != 0)) {
					metric_ = java.util.Collections.unmodifiableList(metric_);
				}
				if (((mutable_bitField0_ & 0x00000001) != 0)) {
					address_ = address_.getUnmodifiableView();
				}
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return metric.MessageOuterClass.internal_static_metric_Message_descriptor;
		}

		@SuppressWarnings({ "rawtypes" })
		@java.lang.Override
		protected com.google.protobuf.MapField internalGetMapField(int number) {
			switch (number) {
			case 9:
				return internalGetProperties();
			default:
				throw new RuntimeException("Invalid map field number: " + number);
			}
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return metric.MessageOuterClass.internal_static_metric_Message_fieldAccessorTable
					.ensureFieldAccessorsInitialized(metric.MessageOuterClass.Message.class,
							metric.MessageOuterClass.Message.Builder.class);
		}

		public interface MetricOrBuilder extends
				// @@protoc_insertion_point(interface_extends:metric.Message.Metric)
				com.google.protobuf.MessageOrBuilder {

			/**
			 * <pre>
			 *Metric Type
			 * </pre>
			 *
			 * <code>string type = 1;</code>
			 * 
			 * @return The type.
			 */
			java.lang.String getType();

			/**
			 * <pre>
			 *Metric Type
			 * </pre>
			 *
			 * <code>string type = 1;</code>
			 * 
			 * @return The bytes for type.
			 */
			com.google.protobuf.ByteString getTypeBytes();

			/**
			 * <pre>
			 *Metric Value
			 * </pre>
			 *
			 * <code>bytes value = 2;</code>
			 * 
			 * @return The value.
			 */
			com.google.protobuf.ByteString getValue();
		}

		/**
		 * Protobuf type {@code metric.Message.Metric}
		 */
		public static final class Metric extends com.google.protobuf.GeneratedMessageV3 implements
				// @@protoc_insertion_point(message_implements:metric.Message.Metric)
				MetricOrBuilder {
			private static final long serialVersionUID = 0L;

			// Use Metric.newBuilder() to construct.
			private Metric(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
				super(builder);
			}

			private Metric() {
				type_ = "";
				value_ = com.google.protobuf.ByteString.EMPTY;
			}

			@java.lang.Override
			@SuppressWarnings({ "unused" })
			protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
				return new Metric();
			}

			@java.lang.Override
			public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
				return this.unknownFields;
			}

			private Metric(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				this();
				if (extensionRegistry == null) {
					throw new java.lang.NullPointerException();
				}
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
						.newBuilder();
				try {
					boolean done = false;
					while (!done) {
						int tag = input.readTag();
						switch (tag) {
						case 0:
							done = true;
							break;
						case 10: {
							java.lang.String s = input.readStringRequireUtf8();

							type_ = s;
							break;
						}
						case 18: {

							value_ = input.readBytes();
							break;
						}
						default: {
							if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
								done = true;
							}
							break;
						}
						}
					}
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					throw e.setUnfinishedMessage(this);
				} catch (java.io.IOException e) {
					throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
				} finally {
					this.unknownFields = unknownFields.build();
					makeExtensionsImmutable();
				}
			}

			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return metric.MessageOuterClass.internal_static_metric_Message_Metric_descriptor;
			}

			@java.lang.Override
			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
				return metric.MessageOuterClass.internal_static_metric_Message_Metric_fieldAccessorTable
						.ensureFieldAccessorsInitialized(metric.MessageOuterClass.Message.Metric.class,
								metric.MessageOuterClass.Message.Metric.Builder.class);
			}

			public static final int TYPE_FIELD_NUMBER = 1;
			private volatile java.lang.Object type_;

			/**
			 * <pre>
			 *Metric Type
			 * </pre>
			 *
			 * <code>string type = 1;</code>
			 * 
			 * @return The type.
			 */
			public java.lang.String getType() {
				java.lang.Object ref = type_;
				if (ref instanceof java.lang.String) {
					return (java.lang.String) ref;
				} else {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					type_ = s;
					return s;
				}
			}

			/**
			 * <pre>
			 *Metric Type
			 * </pre>
			 *
			 * <code>string type = 1;</code>
			 * 
			 * @return The bytes for type.
			 */
			public com.google.protobuf.ByteString getTypeBytes() {
				java.lang.Object ref = type_;
				if (ref instanceof java.lang.String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					type_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			public static final int VALUE_FIELD_NUMBER = 2;
			private com.google.protobuf.ByteString value_;

			/**
			 * <pre>
			 *Metric Value
			 * </pre>
			 *
			 * <code>bytes value = 2;</code>
			 * 
			 * @return The value.
			 */
			public com.google.protobuf.ByteString getValue() {
				return value_;
			}

			private byte memoizedIsInitialized = -1;

			@java.lang.Override
			public final boolean isInitialized() {
				byte isInitialized = memoizedIsInitialized;
				if (isInitialized == 1)
					return true;
				if (isInitialized == 0)
					return false;

				memoizedIsInitialized = 1;
				return true;
			}

			@java.lang.Override
			public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
				if (!getTypeBytes().isEmpty()) {
					com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
				}
				if (!value_.isEmpty()) {
					output.writeBytes(2, value_);
				}
				unknownFields.writeTo(output);
			}

			@java.lang.Override
			public int getSerializedSize() {
				int size = memoizedSize;
				if (size != -1)
					return size;

				size = 0;
				if (!getTypeBytes().isEmpty()) {
					size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
				}
				if (!value_.isEmpty()) {
					size += com.google.protobuf.CodedOutputStream.computeBytesSize(2, value_);
				}
				size += unknownFields.getSerializedSize();
				memoizedSize = size;
				return size;
			}

			@java.lang.Override
			public boolean equals(final java.lang.Object obj) {
				if (obj == this) {
					return true;
				}
				if (!(obj instanceof metric.MessageOuterClass.Message.Metric)) {
					return super.equals(obj);
				}
				metric.MessageOuterClass.Message.Metric other = (metric.MessageOuterClass.Message.Metric) obj;

				if (!getType().equals(other.getType()))
					return false;
				if (!getValue().equals(other.getValue()))
					return false;
				if (!unknownFields.equals(other.unknownFields))
					return false;
				return true;
			}

			@java.lang.Override
			public int hashCode() {
				if (memoizedHashCode != 0) {
					return memoizedHashCode;
				}
				int hash = 41;
				hash = (19 * hash) + getDescriptor().hashCode();
				hash = (37 * hash) + TYPE_FIELD_NUMBER;
				hash = (53 * hash) + getType().hashCode();
				hash = (37 * hash) + VALUE_FIELD_NUMBER;
				hash = (53 * hash) + getValue().hashCode();
				hash = (29 * hash) + unknownFields.hashCode();
				memoizedHashCode = hash;
				return hash;
			}

			public static metric.MessageOuterClass.Message.Metric parseFrom(java.nio.ByteBuffer data)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data);
			}

			public static metric.MessageOuterClass.Message.Metric parseFrom(java.nio.ByteBuffer data,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data, extensionRegistry);
			}

			public static metric.MessageOuterClass.Message.Metric parseFrom(com.google.protobuf.ByteString data)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data);
			}

			public static metric.MessageOuterClass.Message.Metric parseFrom(com.google.protobuf.ByteString data,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data, extensionRegistry);
			}

			public static metric.MessageOuterClass.Message.Metric parseFrom(byte[] data)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data);
			}

			public static metric.MessageOuterClass.Message.Metric parseFrom(byte[] data,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data, extensionRegistry);
			}

			public static metric.MessageOuterClass.Message.Metric parseFrom(java.io.InputStream input)
					throws java.io.IOException {
				return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
			}

			public static metric.MessageOuterClass.Message.Metric parseFrom(java.io.InputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
			}

			public static metric.MessageOuterClass.Message.Metric parseDelimitedFrom(java.io.InputStream input)
					throws java.io.IOException {
				return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
			}

			public static metric.MessageOuterClass.Message.Metric parseDelimitedFrom(java.io.InputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
						extensionRegistry);
			}

			public static metric.MessageOuterClass.Message.Metric parseFrom(com.google.protobuf.CodedInputStream input)
					throws java.io.IOException {
				return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
			}

			public static metric.MessageOuterClass.Message.Metric parseFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
			}

			@java.lang.Override
			public Builder newBuilderForType() {
				return newBuilder();
			}

			public static Builder newBuilder() {
				return DEFAULT_INSTANCE.toBuilder();
			}

			public static Builder newBuilder(metric.MessageOuterClass.Message.Metric prototype) {
				return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
			}

			@java.lang.Override
			public Builder toBuilder() {
				return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
			}

			@java.lang.Override
			protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				Builder builder = new Builder(parent);
				return builder;
			}

			/**
			 * Protobuf type {@code metric.Message.Metric}
			 */
			public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
					// @@protoc_insertion_point(builder_implements:metric.Message.Metric)
					metric.MessageOuterClass.Message.MetricOrBuilder {
				public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
					return metric.MessageOuterClass.internal_static_metric_Message_Metric_descriptor;
				}

				@java.lang.Override
				protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
					return metric.MessageOuterClass.internal_static_metric_Message_Metric_fieldAccessorTable
							.ensureFieldAccessorsInitialized(metric.MessageOuterClass.Message.Metric.class,
									metric.MessageOuterClass.Message.Metric.Builder.class);
				}

				// Construct using metric.MessageOuterClass.Message.Metric.newBuilder()
				private Builder() {
					maybeForceBuilderInitialization();
				}

				private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
					super(parent);
					maybeForceBuilderInitialization();
				}

				private void maybeForceBuilderInitialization() {
					if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
					}
				}

				@java.lang.Override
				public Builder clear() {
					super.clear();
					type_ = "";

					value_ = com.google.protobuf.ByteString.EMPTY;

					return this;
				}

				@java.lang.Override
				public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
					return metric.MessageOuterClass.internal_static_metric_Message_Metric_descriptor;
				}

				@java.lang.Override
				public metric.MessageOuterClass.Message.Metric getDefaultInstanceForType() {
					return metric.MessageOuterClass.Message.Metric.getDefaultInstance();
				}

				@java.lang.Override
				public metric.MessageOuterClass.Message.Metric build() {
					metric.MessageOuterClass.Message.Metric result = buildPartial();
					if (!result.isInitialized()) {
						throw newUninitializedMessageException(result);
					}
					return result;
				}

				@java.lang.Override
				public metric.MessageOuterClass.Message.Metric buildPartial() {
					metric.MessageOuterClass.Message.Metric result = new metric.MessageOuterClass.Message.Metric(this);
					result.type_ = type_;
					result.value_ = value_;
					onBuilt();
					return result;
				}

				@java.lang.Override
				public Builder clone() {
					return super.clone();
				}

				@java.lang.Override
				public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
					return super.setField(field, value);
				}

				@java.lang.Override
				public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
					return super.clearField(field);
				}

				@java.lang.Override
				public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
					return super.clearOneof(oneof);
				}

				@java.lang.Override
				public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
						java.lang.Object value) {
					return super.setRepeatedField(field, index, value);
				}

				@java.lang.Override
				public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
						java.lang.Object value) {
					return super.addRepeatedField(field, value);
				}

				@java.lang.Override
				public Builder mergeFrom(com.google.protobuf.Message other) {
					if (other instanceof metric.MessageOuterClass.Message.Metric) {
						return mergeFrom((metric.MessageOuterClass.Message.Metric) other);
					} else {
						super.mergeFrom(other);
						return this;
					}
				}

				public Builder mergeFrom(metric.MessageOuterClass.Message.Metric other) {
					if (other == metric.MessageOuterClass.Message.Metric.getDefaultInstance())
						return this;
					if (!other.getType().isEmpty()) {
						type_ = other.type_;
						onChanged();
					}
					if (other.getValue() != com.google.protobuf.ByteString.EMPTY) {
						setValue(other.getValue());
					}
					this.mergeUnknownFields(other.unknownFields);
					onChanged();
					return this;
				}

				@java.lang.Override
				public final boolean isInitialized() {
					return true;
				}

				@java.lang.Override
				public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
						com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
					metric.MessageOuterClass.Message.Metric parsedMessage = null;
					try {
						parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
					} catch (com.google.protobuf.InvalidProtocolBufferException e) {
						parsedMessage = (metric.MessageOuterClass.Message.Metric) e.getUnfinishedMessage();
						throw e.unwrapIOException();
					} finally {
						if (parsedMessage != null) {
							mergeFrom(parsedMessage);
						}
					}
					return this;
				}

				private java.lang.Object type_ = "";

				/**
				 * <pre>
				 *Metric Type
				 * </pre>
				 *
				 * <code>string type = 1;</code>
				 * 
				 * @return The type.
				 */
				public java.lang.String getType() {
					java.lang.Object ref = type_;
					if (!(ref instanceof java.lang.String)) {
						com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
						java.lang.String s = bs.toStringUtf8();
						type_ = s;
						return s;
					} else {
						return (java.lang.String) ref;
					}
				}

				/**
				 * <pre>
				 *Metric Type
				 * </pre>
				 *
				 * <code>string type = 1;</code>
				 * 
				 * @return The bytes for type.
				 */
				public com.google.protobuf.ByteString getTypeBytes() {
					java.lang.Object ref = type_;
					if (ref instanceof String) {
						com.google.protobuf.ByteString b = com.google.protobuf.ByteString
								.copyFromUtf8((java.lang.String) ref);
						type_ = b;
						return b;
					} else {
						return (com.google.protobuf.ByteString) ref;
					}
				}

				/**
				 * <pre>
				 *Metric Type
				 * </pre>
				 *
				 * <code>string type = 1;</code>
				 * 
				 * @param value The type to set.
				 * @return This builder for chaining.
				 */
				public Builder setType(java.lang.String value) {
					if (value == null) {
						throw new NullPointerException();
					}

					type_ = value;
					onChanged();
					return this;
				}

				/**
				 * <pre>
				 *Metric Type
				 * </pre>
				 *
				 * <code>string type = 1;</code>
				 * 
				 * @return This builder for chaining.
				 */
				public Builder clearType() {

					type_ = getDefaultInstance().getType();
					onChanged();
					return this;
				}

				/**
				 * <pre>
				 *Metric Type
				 * </pre>
				 *
				 * <code>string type = 1;</code>
				 * 
				 * @param value The bytes for type to set.
				 * @return This builder for chaining.
				 */
				public Builder setTypeBytes(com.google.protobuf.ByteString value) {
					if (value == null) {
						throw new NullPointerException();
					}
					checkByteStringIsUtf8(value);

					type_ = value;
					onChanged();
					return this;
				}

				private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;

				/**
				 * <pre>
				 *Metric Value
				 * </pre>
				 *
				 * <code>bytes value = 2;</code>
				 * 
				 * @return The value.
				 */
				public com.google.protobuf.ByteString getValue() {
					return value_;
				}

				/**
				 * <pre>
				 *Metric Value
				 * </pre>
				 *
				 * <code>bytes value = 2;</code>
				 * 
				 * @param value The value to set.
				 * @return This builder for chaining.
				 */
				public Builder setValue(com.google.protobuf.ByteString value) {
					if (value == null) {
						throw new NullPointerException();
					}

					value_ = value;
					onChanged();
					return this;
				}

				/**
				 * <pre>
				 *Metric Value
				 * </pre>
				 *
				 * <code>bytes value = 2;</code>
				 * 
				 * @return This builder for chaining.
				 */
				public Builder clearValue() {

					value_ = getDefaultInstance().getValue();
					onChanged();
					return this;
				}

				@java.lang.Override
				public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
					return super.setUnknownFields(unknownFields);
				}

				@java.lang.Override
				public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
					return super.mergeUnknownFields(unknownFields);
				}

				// @@protoc_insertion_point(builder_scope:metric.Message.Metric)
			}

			// @@protoc_insertion_point(class_scope:metric.Message.Metric)
			private static final metric.MessageOuterClass.Message.Metric DEFAULT_INSTANCE;
			static {
				DEFAULT_INSTANCE = new metric.MessageOuterClass.Message.Metric();
			}

			public static metric.MessageOuterClass.Message.Metric getDefaultInstance() {
				return DEFAULT_INSTANCE;
			}

			private static final com.google.protobuf.Parser<Metric> PARSER = new com.google.protobuf.AbstractParser<Metric>() {
				@java.lang.Override
				public Metric parsePartialFrom(com.google.protobuf.CodedInputStream input,
						com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
					return new Metric(input, extensionRegistry);
				}
			};

			public static com.google.protobuf.Parser<Metric> parser() {
				return PARSER;
			}

			@java.lang.Override
			public com.google.protobuf.Parser<Metric> getParserForType() {
				return PARSER;
			}

			@java.lang.Override
			public metric.MessageOuterClass.Message.Metric getDefaultInstanceForType() {
				return DEFAULT_INSTANCE;
			}

		}

		public static final int NAMESPACE_FIELD_NUMBER = 3;
		private volatile java.lang.Object namespace_;

		/**
		 * <pre>
		 *Metric Namespace
		 * </pre>
		 *
		 * <code>string namespace = 3;</code>
		 * 
		 * @return The namespace.
		 */
		public java.lang.String getNamespace() {
			java.lang.Object ref = namespace_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				namespace_ = s;
				return s;
			}
		}

		/**
		 * <pre>
		 *Metric Namespace
		 * </pre>
		 *
		 * <code>string namespace = 3;</code>
		 * 
		 * @return The bytes for namespace.
		 */
		public com.google.protobuf.ByteString getNamespaceBytes() {
			java.lang.Object ref = namespace_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				namespace_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int PROCESSNAME_FIELD_NUMBER = 4;
		private volatile java.lang.Object processName_;

		/**
		 * <pre>
		 *Metric Process Name
		 * </pre>
		 *
		 * <code>string processName = 4;</code>
		 * 
		 * @return The processName.
		 */
		public java.lang.String getProcessName() {
			java.lang.Object ref = processName_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				processName_ = s;
				return s;
			}
		}

		/**
		 * <pre>
		 *Metric Process Name
		 * </pre>
		 *
		 * <code>string processName = 4;</code>
		 * 
		 * @return The bytes for processName.
		 */
		public com.google.protobuf.ByteString getProcessNameBytes() {
			java.lang.Object ref = processName_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				processName_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int HOSTNAME_FIELD_NUMBER = 5;
		private volatile java.lang.Object hostName_;

		/**
		 * <pre>
		 *Metric Host Name
		 * </pre>
		 *
		 * <code>string hostName = 5;</code>
		 * 
		 * @return The hostName.
		 */
		public java.lang.String getHostName() {
			java.lang.Object ref = hostName_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				hostName_ = s;
				return s;
			}
		}

		/**
		 * <pre>
		 *Metric Host Name
		 * </pre>
		 *
		 * <code>string hostName = 5;</code>
		 * 
		 * @return The bytes for hostName.
		 */
		public com.google.protobuf.ByteString getHostNameBytes() {
			java.lang.Object ref = hostName_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				hostName_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int TIMESTAMPUNIX_FIELD_NUMBER = 6;
		private long timestampUnix_;

		/**
		 * <pre>
		 *Matric Publish timestamp
		 * </pre>
		 *
		 * <code>int64 timestampUnix = 6;</code>
		 * 
		 * @return The timestampUnix.
		 */
		public long getTimestampUnix() {
			return timestampUnix_;
		}

		public static final int ADDRESS_FIELD_NUMBER = 7;
		private com.google.protobuf.LazyStringList address_;

		/**
		 * <pre>
		 * IPAddress
		 * </pre>
		 *
		 * <code>repeated string address = 7;</code>
		 * 
		 * @return A list containing the address.
		 */
		public com.google.protobuf.ProtocolStringList getAddressList() {
			return address_;
		}

		/**
		 * <pre>
		 * IPAddress
		 * </pre>
		 *
		 * <code>repeated string address = 7;</code>
		 * 
		 * @return The count of address.
		 */
		public int getAddressCount() {
			return address_.size();
		}

		/**
		 * <pre>
		 * IPAddress
		 * </pre>
		 *
		 * <code>repeated string address = 7;</code>
		 * 
		 * @param index The index of the element to return.
		 * @return The address at the given index.
		 */
		public java.lang.String getAddress(int index) {
			return address_.get(index);
		}

		/**
		 * <pre>
		 * IPAddress
		 * </pre>
		 *
		 * <code>repeated string address = 7;</code>
		 * 
		 * @param index The index of the value to return.
		 * @return The bytes of the address at the given index.
		 */
		public com.google.protobuf.ByteString getAddressBytes(int index) {
			return address_.getByteString(index);
		}

		public static final int PROPERTIES_FIELD_NUMBER = 9;

		private static final class PropertiesDefaultEntryHolder {
			static final com.google.protobuf.MapEntry<java.lang.String, java.lang.String> defaultEntry = com.google.protobuf.MapEntry.<java.lang.String, java.lang.String>newDefaultInstance(
					metric.MessageOuterClass.internal_static_metric_Message_PropertiesEntry_descriptor,
					com.google.protobuf.WireFormat.FieldType.STRING, "",
					com.google.protobuf.WireFormat.FieldType.STRING, "");
		}

		private com.google.protobuf.MapField<java.lang.String, java.lang.String> properties_;

		private com.google.protobuf.MapField<java.lang.String, java.lang.String> internalGetProperties() {
			if (properties_ == null) {
				return com.google.protobuf.MapField.emptyMapField(PropertiesDefaultEntryHolder.defaultEntry);
			}
			return properties_;
		}

		public int getPropertiesCount() {
			return internalGetProperties().getMap().size();
		}

		/**
		 * <pre>
		 *Metric Headers like  HostIPAddress
		 * </pre>
		 *
		 * <code>map&lt;string, string&gt; properties = 9;</code>
		 */

		public boolean containsProperties(java.lang.String key) {
			if (key == null) {
				throw new java.lang.NullPointerException();
			}
			return internalGetProperties().getMap().containsKey(key);
		}

		/**
		 * Use {@link #getPropertiesMap()} instead.
		 */
		@java.lang.Deprecated
		public java.util.Map<java.lang.String, java.lang.String> getProperties() {
			return getPropertiesMap();
		}

		/**
		 * <pre>
		 *Metric Headers like  HostIPAddress
		 * </pre>
		 *
		 * <code>map&lt;string, string&gt; properties = 9;</code>
		 */

		public java.util.Map<java.lang.String, java.lang.String> getPropertiesMap() {
			return internalGetProperties().getMap();
		}

		/**
		 * <pre>
		 *Metric Headers like  HostIPAddress
		 * </pre>
		 *
		 * <code>map&lt;string, string&gt; properties = 9;</code>
		 */

		public java.lang.String getPropertiesOrDefault(java.lang.String key, java.lang.String defaultValue) {
			if (key == null) {
				throw new java.lang.NullPointerException();
			}
			java.util.Map<java.lang.String, java.lang.String> map = internalGetProperties().getMap();
			return map.containsKey(key) ? map.get(key) : defaultValue;
		}

		/**
		 * <pre>
		 *Metric Headers like  HostIPAddress
		 * </pre>
		 *
		 * <code>map&lt;string, string&gt; properties = 9;</code>
		 */

		public java.lang.String getPropertiesOrThrow(java.lang.String key) {
			if (key == null) {
				throw new java.lang.NullPointerException();
			}
			java.util.Map<java.lang.String, java.lang.String> map = internalGetProperties().getMap();
			if (!map.containsKey(key)) {
				throw new java.lang.IllegalArgumentException();
			}
			return map.get(key);
		}

		public static final int METRIC_FIELD_NUMBER = 1;
		private java.util.List<metric.MessageOuterClass.Message.Metric> metric_;

		/**
		 * <code>repeated .metric.Message.Metric metric = 1;</code>
		 */
		public java.util.List<metric.MessageOuterClass.Message.Metric> getMetricList() {
			return metric_;
		}

		/**
		 * <code>repeated .metric.Message.Metric metric = 1;</code>
		 */
		public java.util.List<? extends metric.MessageOuterClass.Message.MetricOrBuilder> getMetricOrBuilderList() {
			return metric_;
		}

		/**
		 * <code>repeated .metric.Message.Metric metric = 1;</code>
		 */
		public int getMetricCount() {
			return metric_.size();
		}

		/**
		 * <code>repeated .metric.Message.Metric metric = 1;</code>
		 */
		public metric.MessageOuterClass.Message.Metric getMetric(int index) {
			return metric_.get(index);
		}

		/**
		 * <code>repeated .metric.Message.Metric metric = 1;</code>
		 */
		public metric.MessageOuterClass.Message.MetricOrBuilder getMetricOrBuilder(int index) {
			return metric_.get(index);
		}

		private byte memoizedIsInitialized = -1;

		@java.lang.Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1)
				return true;
			if (isInitialized == 0)
				return false;

			memoizedIsInitialized = 1;
			return true;
		}

		@java.lang.Override
		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			for (int i = 0; i < metric_.size(); i++) {
				output.writeMessage(1, metric_.get(i));
			}
			if (!getNamespaceBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 3, namespace_);
			}
			if (!getProcessNameBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 4, processName_);
			}
			if (!getHostNameBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 5, hostName_);
			}
			if (timestampUnix_ != 0L) {
				output.writeInt64(6, timestampUnix_);
			}
			for (int i = 0; i < address_.size(); i++) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 7, address_.getRaw(i));
			}
			com.google.protobuf.GeneratedMessageV3.serializeStringMapTo(output, internalGetProperties(),
					PropertiesDefaultEntryHolder.defaultEntry, 9);
			unknownFields.writeTo(output);
		}

		@java.lang.Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1)
				return size;

			size = 0;
			for (int i = 0; i < metric_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, metric_.get(i));
			}
			if (!getNamespaceBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, namespace_);
			}
			if (!getProcessNameBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, processName_);
			}
			if (!getHostNameBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, hostName_);
			}
			if (timestampUnix_ != 0L) {
				size += com.google.protobuf.CodedOutputStream.computeInt64Size(6, timestampUnix_);
			}
			{
				int dataSize = 0;
				for (int i = 0; i < address_.size(); i++) {
					dataSize += computeStringSizeNoTag(address_.getRaw(i));
				}
				size += dataSize;
				size += 1 * getAddressList().size();
			}
			for (java.util.Map.Entry<java.lang.String, java.lang.String> entry : internalGetProperties().getMap()
					.entrySet()) {
				com.google.protobuf.MapEntry<java.lang.String, java.lang.String> properties__ = PropertiesDefaultEntryHolder.defaultEntry
						.newBuilderForType().setKey(entry.getKey()).setValue(entry.getValue()).build();
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(9, properties__);
			}
			size += unknownFields.getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof metric.MessageOuterClass.Message)) {
				return super.equals(obj);
			}
			metric.MessageOuterClass.Message other = (metric.MessageOuterClass.Message) obj;

			if (!getNamespace().equals(other.getNamespace()))
				return false;
			if (!getProcessName().equals(other.getProcessName()))
				return false;
			if (!getHostName().equals(other.getHostName()))
				return false;
			if (getTimestampUnix() != other.getTimestampUnix())
				return false;
			if (!getAddressList().equals(other.getAddressList()))
				return false;
			if (!internalGetProperties().equals(other.internalGetProperties()))
				return false;
			if (!getMetricList().equals(other.getMetricList()))
				return false;
			if (!unknownFields.equals(other.unknownFields))
				return false;
			return true;
		}

		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			hash = (37 * hash) + NAMESPACE_FIELD_NUMBER;
			hash = (53 * hash) + getNamespace().hashCode();
			hash = (37 * hash) + PROCESSNAME_FIELD_NUMBER;
			hash = (53 * hash) + getProcessName().hashCode();
			hash = (37 * hash) + HOSTNAME_FIELD_NUMBER;
			hash = (53 * hash) + getHostName().hashCode();
			hash = (37 * hash) + TIMESTAMPUNIX_FIELD_NUMBER;
			hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getTimestampUnix());
			if (getAddressCount() > 0) {
				hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
				hash = (53 * hash) + getAddressList().hashCode();
			}
			if (!internalGetProperties().getMap().isEmpty()) {
				hash = (37 * hash) + PROPERTIES_FIELD_NUMBER;
				hash = (53 * hash) + internalGetProperties().hashCode();
			}
			if (getMetricCount() > 0) {
				hash = (37 * hash) + METRIC_FIELD_NUMBER;
				hash = (53 * hash) + getMetricList().hashCode();
			}
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static metric.MessageOuterClass.Message parseFrom(java.nio.ByteBuffer data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static metric.MessageOuterClass.Message parseFrom(java.nio.ByteBuffer data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static metric.MessageOuterClass.Message parseFrom(com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static metric.MessageOuterClass.Message parseFrom(com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static metric.MessageOuterClass.Message parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static metric.MessageOuterClass.Message parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static metric.MessageOuterClass.Message parseFrom(java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}

		public static metric.MessageOuterClass.Message parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static metric.MessageOuterClass.Message parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
		}

		public static metric.MessageOuterClass.Message parseDelimitedFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
					extensionRegistry);
		}

		public static metric.MessageOuterClass.Message parseFrom(com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
		}

		public static metric.MessageOuterClass.Message parseFrom(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
		}

		@java.lang.Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(metric.MessageOuterClass.Message prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		@java.lang.Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code metric.Message}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
				// @@protoc_insertion_point(builder_implements:metric.Message)
				metric.MessageOuterClass.MessageOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return metric.MessageOuterClass.internal_static_metric_Message_descriptor;
			}

			@SuppressWarnings({ "rawtypes" })
			protected com.google.protobuf.MapField internalGetMapField(int number) {
				switch (number) {
				case 9:
					return internalGetProperties();
				default:
					throw new RuntimeException("Invalid map field number: " + number);
				}
			}

			@SuppressWarnings({ "rawtypes" })
			protected com.google.protobuf.MapField internalGetMutableMapField(int number) {
				switch (number) {
				case 9:
					return internalGetMutableProperties();
				default:
					throw new RuntimeException("Invalid map field number: " + number);
				}
			}

			@java.lang.Override
			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
				return metric.MessageOuterClass.internal_static_metric_Message_fieldAccessorTable
						.ensureFieldAccessorsInitialized(metric.MessageOuterClass.Message.class,
								metric.MessageOuterClass.Message.Builder.class);
			}

			// Construct using metric.MessageOuterClass.Message.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
					getMetricFieldBuilder();
				}
			}

			@java.lang.Override
			public Builder clear() {
				super.clear();
				namespace_ = "";

				processName_ = "";

				hostName_ = "";

				timestampUnix_ = 0L;

				address_ = com.google.protobuf.LazyStringArrayList.EMPTY;
				bitField0_ = (bitField0_ & ~0x00000001);
				internalGetMutableProperties().clear();
				if (metricBuilder_ == null) {
					metric_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000004);
				} else {
					metricBuilder_.clear();
				}
				return this;
			}

			@java.lang.Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return metric.MessageOuterClass.internal_static_metric_Message_descriptor;
			}

			@java.lang.Override
			public metric.MessageOuterClass.Message getDefaultInstanceForType() {
				return metric.MessageOuterClass.Message.getDefaultInstance();
			}

			@java.lang.Override
			public metric.MessageOuterClass.Message build() {
				metric.MessageOuterClass.Message result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@java.lang.Override
			public metric.MessageOuterClass.Message buildPartial() {
				metric.MessageOuterClass.Message result = new metric.MessageOuterClass.Message(this);
				int from_bitField0_ = bitField0_;
				result.namespace_ = namespace_;
				result.processName_ = processName_;
				result.hostName_ = hostName_;
				result.timestampUnix_ = timestampUnix_;
				if (((bitField0_ & 0x00000001) != 0)) {
					address_ = address_.getUnmodifiableView();
					bitField0_ = (bitField0_ & ~0x00000001);
				}
				result.address_ = address_;
				result.properties_ = internalGetProperties();
				result.properties_.makeImmutable();
				if (metricBuilder_ == null) {
					if (((bitField0_ & 0x00000004) != 0)) {
						metric_ = java.util.Collections.unmodifiableList(metric_);
						bitField0_ = (bitField0_ & ~0x00000004);
					}
					result.metric_ = metric_;
				} else {
					result.metric_ = metricBuilder_.build();
				}
				onBuilt();
				return result;
			}

			@java.lang.Override
			public Builder clone() {
				return super.clone();
			}

			@java.lang.Override
			public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
				return super.setField(field, value);
			}

			@java.lang.Override
			public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
				return super.clearField(field);
			}

			@java.lang.Override
			public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return super.clearOneof(oneof);
			}

			@java.lang.Override
			public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
					java.lang.Object value) {
				return super.setRepeatedField(field, index, value);
			}

			@java.lang.Override
			public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
					java.lang.Object value) {
				return super.addRepeatedField(field, value);
			}

			@java.lang.Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof metric.MessageOuterClass.Message) {
					return mergeFrom((metric.MessageOuterClass.Message) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(metric.MessageOuterClass.Message other) {
				if (other == metric.MessageOuterClass.Message.getDefaultInstance())
					return this;
				if (!other.getNamespace().isEmpty()) {
					namespace_ = other.namespace_;
					onChanged();
				}
				if (!other.getProcessName().isEmpty()) {
					processName_ = other.processName_;
					onChanged();
				}
				if (!other.getHostName().isEmpty()) {
					hostName_ = other.hostName_;
					onChanged();
				}
				if (other.getTimestampUnix() != 0L) {
					setTimestampUnix(other.getTimestampUnix());
				}
				if (!other.address_.isEmpty()) {
					if (address_.isEmpty()) {
						address_ = other.address_;
						bitField0_ = (bitField0_ & ~0x00000001);
					} else {
						ensureAddressIsMutable();
						address_.addAll(other.address_);
					}
					onChanged();
				}
				internalGetMutableProperties().mergeFrom(other.internalGetProperties());
				if (metricBuilder_ == null) {
					if (!other.metric_.isEmpty()) {
						if (metric_.isEmpty()) {
							metric_ = other.metric_;
							bitField0_ = (bitField0_ & ~0x00000004);
						} else {
							ensureMetricIsMutable();
							metric_.addAll(other.metric_);
						}
						onChanged();
					}
				} else {
					if (!other.metric_.isEmpty()) {
						if (metricBuilder_.isEmpty()) {
							metricBuilder_.dispose();
							metricBuilder_ = null;
							metric_ = other.metric_;
							bitField0_ = (bitField0_ & ~0x00000004);
							metricBuilder_ = com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
									? getMetricFieldBuilder()
									: null;
						} else {
							metricBuilder_.addAllMessages(other.metric_);
						}
					}
				}
				this.mergeUnknownFields(other.unknownFields);
				onChanged();
				return this;
			}

			@java.lang.Override
			public final boolean isInitialized() {
				return true;
			}

			@java.lang.Override
			public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				metric.MessageOuterClass.Message parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (metric.MessageOuterClass.Message) e.getUnfinishedMessage();
					throw e.unwrapIOException();
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			private java.lang.Object namespace_ = "";

			/**
			 * <pre>
			 *Metric Namespace
			 * </pre>
			 *
			 * <code>string namespace = 3;</code>
			 * 
			 * @return The namespace.
			 */
			public java.lang.String getNamespace() {
				java.lang.Object ref = namespace_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					namespace_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <pre>
			 *Metric Namespace
			 * </pre>
			 *
			 * <code>string namespace = 3;</code>
			 * 
			 * @return The bytes for namespace.
			 */
			public com.google.protobuf.ByteString getNamespaceBytes() {
				java.lang.Object ref = namespace_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					namespace_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <pre>
			 *Metric Namespace
			 * </pre>
			 *
			 * <code>string namespace = 3;</code>
			 * 
			 * @param value The namespace to set.
			 * @return This builder for chaining.
			 */
			public Builder setNamespace(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				namespace_ = value;
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 *Metric Namespace
			 * </pre>
			 *
			 * <code>string namespace = 3;</code>
			 * 
			 * @return This builder for chaining.
			 */
			public Builder clearNamespace() {

				namespace_ = getDefaultInstance().getNamespace();
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 *Metric Namespace
			 * </pre>
			 *
			 * <code>string namespace = 3;</code>
			 * 
			 * @param value The bytes for namespace to set.
			 * @return This builder for chaining.
			 */
			public Builder setNamespaceBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				namespace_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object processName_ = "";

			/**
			 * <pre>
			 *Metric Process Name
			 * </pre>
			 *
			 * <code>string processName = 4;</code>
			 * 
			 * @return The processName.
			 */
			public java.lang.String getProcessName() {
				java.lang.Object ref = processName_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					processName_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <pre>
			 *Metric Process Name
			 * </pre>
			 *
			 * <code>string processName = 4;</code>
			 * 
			 * @return The bytes for processName.
			 */
			public com.google.protobuf.ByteString getProcessNameBytes() {
				java.lang.Object ref = processName_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					processName_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <pre>
			 *Metric Process Name
			 * </pre>
			 *
			 * <code>string processName = 4;</code>
			 * 
			 * @param value The processName to set.
			 * @return This builder for chaining.
			 */
			public Builder setProcessName(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				processName_ = value;
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 *Metric Process Name
			 * </pre>
			 *
			 * <code>string processName = 4;</code>
			 * 
			 * @return This builder for chaining.
			 */
			public Builder clearProcessName() {

				processName_ = getDefaultInstance().getProcessName();
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 *Metric Process Name
			 * </pre>
			 *
			 * <code>string processName = 4;</code>
			 * 
			 * @param value The bytes for processName to set.
			 * @return This builder for chaining.
			 */
			public Builder setProcessNameBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				processName_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object hostName_ = "";

			/**
			 * <pre>
			 *Metric Host Name
			 * </pre>
			 *
			 * <code>string hostName = 5;</code>
			 * 
			 * @return The hostName.
			 */
			public java.lang.String getHostName() {
				java.lang.Object ref = hostName_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					hostName_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <pre>
			 *Metric Host Name
			 * </pre>
			 *
			 * <code>string hostName = 5;</code>
			 * 
			 * @return The bytes for hostName.
			 */
			public com.google.protobuf.ByteString getHostNameBytes() {
				java.lang.Object ref = hostName_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					hostName_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <pre>
			 *Metric Host Name
			 * </pre>
			 *
			 * <code>string hostName = 5;</code>
			 * 
			 * @param value The hostName to set.
			 * @return This builder for chaining.
			 */
			public Builder setHostName(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				hostName_ = value;
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 *Metric Host Name
			 * </pre>
			 *
			 * <code>string hostName = 5;</code>
			 * 
			 * @return This builder for chaining.
			 */
			public Builder clearHostName() {

				hostName_ = getDefaultInstance().getHostName();
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 *Metric Host Name
			 * </pre>
			 *
			 * <code>string hostName = 5;</code>
			 * 
			 * @param value The bytes for hostName to set.
			 * @return This builder for chaining.
			 */
			public Builder setHostNameBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				hostName_ = value;
				onChanged();
				return this;
			}

			private long timestampUnix_;

			/**
			 * <pre>
			 *Matric Publish timestamp
			 * </pre>
			 *
			 * <code>int64 timestampUnix = 6;</code>
			 * 
			 * @return The timestampUnix.
			 */
			public long getTimestampUnix() {
				return timestampUnix_;
			}

			/**
			 * <pre>
			 *Matric Publish timestamp
			 * </pre>
			 *
			 * <code>int64 timestampUnix = 6;</code>
			 * 
			 * @param value The timestampUnix to set.
			 * @return This builder for chaining.
			 */
			public Builder setTimestampUnix(long value) {

				timestampUnix_ = value;
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 *Matric Publish timestamp
			 * </pre>
			 *
			 * <code>int64 timestampUnix = 6;</code>
			 * 
			 * @return This builder for chaining.
			 */
			public Builder clearTimestampUnix() {

				timestampUnix_ = 0L;
				onChanged();
				return this;
			}

			private com.google.protobuf.LazyStringList address_ = com.google.protobuf.LazyStringArrayList.EMPTY;

			private void ensureAddressIsMutable() {
				if (!((bitField0_ & 0x00000001) != 0)) {
					address_ = new com.google.protobuf.LazyStringArrayList(address_);
					bitField0_ |= 0x00000001;
				}
			}

			/**
			 * <pre>
			 * IPAddress
			 * </pre>
			 *
			 * <code>repeated string address = 7;</code>
			 * 
			 * @return A list containing the address.
			 */
			public com.google.protobuf.ProtocolStringList getAddressList() {
				return address_.getUnmodifiableView();
			}

			/**
			 * <pre>
			 * IPAddress
			 * </pre>
			 *
			 * <code>repeated string address = 7;</code>
			 * 
			 * @return The count of address.
			 */
			public int getAddressCount() {
				return address_.size();
			}

			/**
			 * <pre>
			 * IPAddress
			 * </pre>
			 *
			 * <code>repeated string address = 7;</code>
			 * 
			 * @param index The index of the element to return.
			 * @return The address at the given index.
			 */
			public java.lang.String getAddress(int index) {
				return address_.get(index);
			}

			/**
			 * <pre>
			 * IPAddress
			 * </pre>
			 *
			 * <code>repeated string address = 7;</code>
			 * 
			 * @param index The index of the value to return.
			 * @return The bytes of the address at the given index.
			 */
			public com.google.protobuf.ByteString getAddressBytes(int index) {
				return address_.getByteString(index);
			}

			/**
			 * <pre>
			 * IPAddress
			 * </pre>
			 *
			 * <code>repeated string address = 7;</code>
			 * 
			 * @param index The index to set the value at.
			 * @param value The address to set.
			 * @return This builder for chaining.
			 */
			public Builder setAddress(int index, java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureAddressIsMutable();
				address_.set(index, value);
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * IPAddress
			 * </pre>
			 *
			 * <code>repeated string address = 7;</code>
			 * 
			 * @param value The address to add.
			 * @return This builder for chaining.
			 */
			public Builder addAddress(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureAddressIsMutable();
				address_.add(value);
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * IPAddress
			 * </pre>
			 *
			 * <code>repeated string address = 7;</code>
			 * 
			 * @param values The address to add.
			 * @return This builder for chaining.
			 */
			public Builder addAllAddress(java.lang.Iterable<java.lang.String> values) {
				ensureAddressIsMutable();
				com.google.protobuf.AbstractMessageLite.Builder.addAll(values, address_);
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * IPAddress
			 * </pre>
			 *
			 * <code>repeated string address = 7;</code>
			 * 
			 * @return This builder for chaining.
			 */
			public Builder clearAddress() {
				address_ = com.google.protobuf.LazyStringArrayList.EMPTY;
				bitField0_ = (bitField0_ & ~0x00000001);
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * IPAddress
			 * </pre>
			 *
			 * <code>repeated string address = 7;</code>
			 * 
			 * @param value The bytes of the address to add.
			 * @return This builder for chaining.
			 */
			public Builder addAddressBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);
				ensureAddressIsMutable();
				address_.add(value);
				onChanged();
				return this;
			}

			private com.google.protobuf.MapField<java.lang.String, java.lang.String> properties_;

			private com.google.protobuf.MapField<java.lang.String, java.lang.String> internalGetProperties() {
				if (properties_ == null) {
					return com.google.protobuf.MapField.emptyMapField(PropertiesDefaultEntryHolder.defaultEntry);
				}
				return properties_;
			}

			private com.google.protobuf.MapField<java.lang.String, java.lang.String> internalGetMutableProperties() {
				onChanged();
				;
				if (properties_ == null) {
					properties_ = com.google.protobuf.MapField.newMapField(PropertiesDefaultEntryHolder.defaultEntry);
				}
				if (!properties_.isMutable()) {
					properties_ = properties_.copy();
				}
				return properties_;
			}

			public int getPropertiesCount() {
				return internalGetProperties().getMap().size();
			}

			/**
			 * <pre>
			 *Metric Headers like  HostIPAddress
			 * </pre>
			 *
			 * <code>map&lt;string, string&gt; properties = 9;</code>
			 */

			public boolean containsProperties(java.lang.String key) {
				if (key == null) {
					throw new java.lang.NullPointerException();
				}
				return internalGetProperties().getMap().containsKey(key);
			}

			/**
			 * Use {@link #getPropertiesMap()} instead.
			 */
			@java.lang.Deprecated
			public java.util.Map<java.lang.String, java.lang.String> getProperties() {
				return getPropertiesMap();
			}

			/**
			 * <pre>
			 *Metric Headers like  HostIPAddress
			 * </pre>
			 *
			 * <code>map&lt;string, string&gt; properties = 9;</code>
			 */

			public java.util.Map<java.lang.String, java.lang.String> getPropertiesMap() {
				return internalGetProperties().getMap();
			}

			/**
			 * <pre>
			 *Metric Headers like  HostIPAddress
			 * </pre>
			 *
			 * <code>map&lt;string, string&gt; properties = 9;</code>
			 */

			public java.lang.String getPropertiesOrDefault(java.lang.String key, java.lang.String defaultValue) {
				if (key == null) {
					throw new java.lang.NullPointerException();
				}
				java.util.Map<java.lang.String, java.lang.String> map = internalGetProperties().getMap();
				return map.containsKey(key) ? map.get(key) : defaultValue;
			}

			/**
			 * <pre>
			 *Metric Headers like  HostIPAddress
			 * </pre>
			 *
			 * <code>map&lt;string, string&gt; properties = 9;</code>
			 */

			public java.lang.String getPropertiesOrThrow(java.lang.String key) {
				if (key == null) {
					throw new java.lang.NullPointerException();
				}
				java.util.Map<java.lang.String, java.lang.String> map = internalGetProperties().getMap();
				if (!map.containsKey(key)) {
					throw new java.lang.IllegalArgumentException();
				}
				return map.get(key);
			}

			public Builder clearProperties() {
				internalGetMutableProperties().getMutableMap().clear();
				return this;
			}

			/**
			 * <pre>
			 *Metric Headers like  HostIPAddress
			 * </pre>
			 *
			 * <code>map&lt;string, string&gt; properties = 9;</code>
			 */

			public Builder removeProperties(java.lang.String key) {
				if (key == null) {
					throw new java.lang.NullPointerException();
				}
				internalGetMutableProperties().getMutableMap().remove(key);
				return this;
			}

			/**
			 * Use alternate mutation accessors instead.
			 */
			@java.lang.Deprecated
			public java.util.Map<java.lang.String, java.lang.String> getMutableProperties() {
				return internalGetMutableProperties().getMutableMap();
			}

			/**
			 * <pre>
			 *Metric Headers like  HostIPAddress
			 * </pre>
			 *
			 * <code>map&lt;string, string&gt; properties = 9;</code>
			 */
			public Builder putProperties(java.lang.String key, java.lang.String value) {
				if (key == null) {
					throw new java.lang.NullPointerException();
				}
				if (value == null) {
					throw new java.lang.NullPointerException();
				}
				internalGetMutableProperties().getMutableMap().put(key, value);
				return this;
			}

			/**
			 * <pre>
			 *Metric Headers like  HostIPAddress
			 * </pre>
			 *
			 * <code>map&lt;string, string&gt; properties = 9;</code>
			 */

			public Builder putAllProperties(java.util.Map<java.lang.String, java.lang.String> values) {
				internalGetMutableProperties().getMutableMap().putAll(values);
				return this;
			}

			private java.util.List<metric.MessageOuterClass.Message.Metric> metric_ = java.util.Collections.emptyList();

			private void ensureMetricIsMutable() {
				if (!((bitField0_ & 0x00000004) != 0)) {
					metric_ = new java.util.ArrayList<metric.MessageOuterClass.Message.Metric>(metric_);
					bitField0_ |= 0x00000004;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilderV3<metric.MessageOuterClass.Message.Metric, metric.MessageOuterClass.Message.Metric.Builder, metric.MessageOuterClass.Message.MetricOrBuilder> metricBuilder_;

			/**
			 * <code>repeated .metric.Message.Metric metric = 1;</code>
			 */
			public java.util.List<metric.MessageOuterClass.Message.Metric> getMetricList() {
				if (metricBuilder_ == null) {
					return java.util.Collections.unmodifiableList(metric_);
				} else {
					return metricBuilder_.getMessageList();
				}
			}

			/**
			 * <code>repeated .metric.Message.Metric metric = 1;</code>
			 */
			public int getMetricCount() {
				if (metricBuilder_ == null) {
					return metric_.size();
				} else {
					return metricBuilder_.getCount();
				}
			}

			/**
			 * <code>repeated .metric.Message.Metric metric = 1;</code>
			 */
			public metric.MessageOuterClass.Message.Metric getMetric(int index) {
				if (metricBuilder_ == null) {
					return metric_.get(index);
				} else {
					return metricBuilder_.getMessage(index);
				}
			}

			/**
			 * <code>repeated .metric.Message.Metric metric = 1;</code>
			 */
			public Builder setMetric(int index, metric.MessageOuterClass.Message.Metric value) {
				if (metricBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureMetricIsMutable();
					metric_.set(index, value);
					onChanged();
				} else {
					metricBuilder_.setMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .metric.Message.Metric metric = 1;</code>
			 */
			public Builder setMetric(int index, metric.MessageOuterClass.Message.Metric.Builder builderForValue) {
				if (metricBuilder_ == null) {
					ensureMetricIsMutable();
					metric_.set(index, builderForValue.build());
					onChanged();
				} else {
					metricBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .metric.Message.Metric metric = 1;</code>
			 */
			public Builder addMetric(metric.MessageOuterClass.Message.Metric value) {
				if (metricBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureMetricIsMutable();
					metric_.add(value);
					onChanged();
				} else {
					metricBuilder_.addMessage(value);
				}
				return this;
			}

			/**
			 * <code>repeated .metric.Message.Metric metric = 1;</code>
			 */
			public Builder addMetric(int index, metric.MessageOuterClass.Message.Metric value) {
				if (metricBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureMetricIsMutable();
					metric_.add(index, value);
					onChanged();
				} else {
					metricBuilder_.addMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .metric.Message.Metric metric = 1;</code>
			 */
			public Builder addMetric(metric.MessageOuterClass.Message.Metric.Builder builderForValue) {
				if (metricBuilder_ == null) {
					ensureMetricIsMutable();
					metric_.add(builderForValue.build());
					onChanged();
				} else {
					metricBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .metric.Message.Metric metric = 1;</code>
			 */
			public Builder addMetric(int index, metric.MessageOuterClass.Message.Metric.Builder builderForValue) {
				if (metricBuilder_ == null) {
					ensureMetricIsMutable();
					metric_.add(index, builderForValue.build());
					onChanged();
				} else {
					metricBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .metric.Message.Metric metric = 1;</code>
			 */
			public Builder addAllMetric(java.lang.Iterable<? extends metric.MessageOuterClass.Message.Metric> values) {
				if (metricBuilder_ == null) {
					ensureMetricIsMutable();
					com.google.protobuf.AbstractMessageLite.Builder.addAll(values, metric_);
					onChanged();
				} else {
					metricBuilder_.addAllMessages(values);
				}
				return this;
			}

			/**
			 * <code>repeated .metric.Message.Metric metric = 1;</code>
			 */
			public Builder clearMetric() {
				if (metricBuilder_ == null) {
					metric_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000004);
					onChanged();
				} else {
					metricBuilder_.clear();
				}
				return this;
			}

			/**
			 * <code>repeated .metric.Message.Metric metric = 1;</code>
			 */
			public Builder removeMetric(int index) {
				if (metricBuilder_ == null) {
					ensureMetricIsMutable();
					metric_.remove(index);
					onChanged();
				} else {
					metricBuilder_.remove(index);
				}
				return this;
			}

			/**
			 * <code>repeated .metric.Message.Metric metric = 1;</code>
			 */
			public metric.MessageOuterClass.Message.Metric.Builder getMetricBuilder(int index) {
				return getMetricFieldBuilder().getBuilder(index);
			}

			/**
			 * <code>repeated .metric.Message.Metric metric = 1;</code>
			 */
			public metric.MessageOuterClass.Message.MetricOrBuilder getMetricOrBuilder(int index) {
				if (metricBuilder_ == null) {
					return metric_.get(index);
				} else {
					return metricBuilder_.getMessageOrBuilder(index);
				}
			}

			/**
			 * <code>repeated .metric.Message.Metric metric = 1;</code>
			 */
			public java.util.List<? extends metric.MessageOuterClass.Message.MetricOrBuilder> getMetricOrBuilderList() {
				if (metricBuilder_ != null) {
					return metricBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(metric_);
				}
			}

			/**
			 * <code>repeated .metric.Message.Metric metric = 1;</code>
			 */
			public metric.MessageOuterClass.Message.Metric.Builder addMetricBuilder() {
				return getMetricFieldBuilder().addBuilder(metric.MessageOuterClass.Message.Metric.getDefaultInstance());
			}

			/**
			 * <code>repeated .metric.Message.Metric metric = 1;</code>
			 */
			public metric.MessageOuterClass.Message.Metric.Builder addMetricBuilder(int index) {
				return getMetricFieldBuilder().addBuilder(index,
						metric.MessageOuterClass.Message.Metric.getDefaultInstance());
			}

			/**
			 * <code>repeated .metric.Message.Metric metric = 1;</code>
			 */
			public java.util.List<metric.MessageOuterClass.Message.Metric.Builder> getMetricBuilderList() {
				return getMetricFieldBuilder().getBuilderList();
			}

			private com.google.protobuf.RepeatedFieldBuilderV3<metric.MessageOuterClass.Message.Metric, metric.MessageOuterClass.Message.Metric.Builder, metric.MessageOuterClass.Message.MetricOrBuilder> getMetricFieldBuilder() {
				if (metricBuilder_ == null) {
					metricBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<metric.MessageOuterClass.Message.Metric, metric.MessageOuterClass.Message.Metric.Builder, metric.MessageOuterClass.Message.MetricOrBuilder>(
							metric_, ((bitField0_ & 0x00000004) != 0), getParentForChildren(), isClean());
					metric_ = null;
				}
				return metricBuilder_;
			}

			@java.lang.Override
			public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFields(unknownFields);
			}

			@java.lang.Override
			public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}

			// @@protoc_insertion_point(builder_scope:metric.Message)
		}

		// @@protoc_insertion_point(class_scope:metric.Message)
		private static final metric.MessageOuterClass.Message DEFAULT_INSTANCE;
		static {
			DEFAULT_INSTANCE = new metric.MessageOuterClass.Message();
		}

		public static metric.MessageOuterClass.Message getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<Message> PARSER = new com.google.protobuf.AbstractParser<Message>() {
			@java.lang.Override
			public Message parsePartialFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new Message(input, extensionRegistry);
			}
		};

		public static com.google.protobuf.Parser<Message> parser() {
			return PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<Message> getParserForType() {
			return PARSER;
		}

		@java.lang.Override
		public metric.MessageOuterClass.Message getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	private static final com.google.protobuf.Descriptors.Descriptor internal_static_metric_Message_descriptor;
	private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_metric_Message_fieldAccessorTable;
	private static final com.google.protobuf.Descriptors.Descriptor internal_static_metric_Message_PropertiesEntry_descriptor;
	private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_metric_Message_PropertiesEntry_fieldAccessorTable;
	private static final com.google.protobuf.Descriptors.Descriptor internal_static_metric_Message_Metric_descriptor;
	private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_metric_Message_Metric_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\rmessage.proto\022\006metric\"\242\002\n\007Message\022\021\n\tn"
				+ "amespace\030\003 \001(\t\022\023\n\013processName\030\004 \001(\t\022\020\n\010h"
				+ "ostName\030\005 \001(\t\022\025\n\rtimestampUnix\030\006 \001(\003\022\017\n\007"
				+ "address\030\007 \003(\t\0223\n\nproperties\030\t \003(\0132\037.metr"
				+ "ic.Message.PropertiesEntry\022&\n\006metric\030\001 \003"
				+ "(\0132\026.metric.Message.Metric\0321\n\017Properties"
				+ "Entry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\032%\n"
				+ "\006Metric\022\014\n\004type\030\001 \001(\t\022\r\n\005value\030\002 \001(\014b\006pr" + "oto3" };
		descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
				new com.google.protobuf.Descriptors.FileDescriptor[] {});
		internal_static_metric_Message_descriptor = getDescriptor().getMessageTypes().get(0);
		internal_static_metric_Message_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_metric_Message_descriptor, new java.lang.String[] { "Namespace", "ProcessName",
						"HostName", "TimestampUnix", "Address", "Properties", "Metric", });
		internal_static_metric_Message_PropertiesEntry_descriptor = internal_static_metric_Message_descriptor
				.getNestedTypes().get(0);
		internal_static_metric_Message_PropertiesEntry_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_metric_Message_PropertiesEntry_descriptor, new java.lang.String[] { "Key", "Value", });
		internal_static_metric_Message_Metric_descriptor = internal_static_metric_Message_descriptor.getNestedTypes()
				.get(1);
		internal_static_metric_Message_Metric_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_metric_Message_Metric_descriptor, new java.lang.String[] { "Type", "Value", });
	}

	// @@protoc_insertion_point(outer_class_scope)
}
